function fixedId(value: number) {
  return `00000000-0000-4000-8000-${value.toString().padStart(12, "0")}`;
}

export const seedIds = {
  firm: fixedId(1),
  staff: Array.from({ length: 12 }, (_, index) => fixedId(10 + index)),
  contacts: Array.from({ length: 6 }, (_, index) => fixedId(100 + index)),
  interactions: Array.from({ length: 6 }, (_, index) => fixedId(200 + index)),
  leads: Array.from({ length: 4 }, (_, index) => fixedId(300 + index)),
  matters: Array.from({ length: 5 }, (_, index) => fixedId(400 + index)),
  tasks: Array.from({ length: 4 }, (_, index) => fixedId(500 + index)),
  deadlines: Array.from({ length: 3 }, (_, index) => fixedId(600 + index)),
  documents: Array.from({ length: 4 }, (_, index) => fixedId(700 + index)),
  requests: Array.from({ length: 3 }, (_, index) => fixedId(800 + index)),
  runs: Array.from({ length: 5 }, (_, index) => fixedId(900 + index)),
  briefs: Array.from({ length: 2 }, (_, index) => fixedId(1000 + index)),
  documentResults: Array.from({ length: 2 }, (_, index) => fixedId(1100 + index)),
  stalledReport: fixedId(1200),
  stalledItems: Array.from({ length: 4 }, (_, index) => fixedId(1300 + index)),
} as const;

const createdAt = "2026-08-29T09:00:00.000Z";
const firmName = process.env.FIRM_NAME?.trim() || "Briar & Calder LLP";

export const seedData = {
  firms: [
    {
      id: seedIds.firm,
      name: firmName,
      profile_json: {
        location: "Los Angeles, California",
        practice_areas: ["employment", "personal_injury", "commercial_litigation"],
        intake_rule: "Prepare the facts and recommendation. A partner decides whether to engage.",
      },
      created_at: createdAt,
    },
  ],
  staff: [
    ["Mara Calder", "partner", "mara@briarcalder.example"],
    ["Elias Briar", "partner", "elias@briarcalder.example"],
    ["Nina Shah", "partner", "nina@briarcalder.example"],
    ["Thomas Reed", "partner", "thomas@briarcalder.example"],
    ["Avery Chen", "associate", "avery@briarcalder.example"],
    ["Jordan Miles", "associate", "jordan@briarcalder.example"],
    ["Leah Ortiz", "associate", "leah@briarcalder.example"],
    ["Sam Patel", "paralegal", "sam@briarcalder.example"],
    ["Priya Nwosu", "paralegal", "priya@briarcalder.example"],
    ["Ana Flores", "intake_coordinator", "ana@briarcalder.example"],
    ["Miles Bennett", "office_manager", "miles@briarcalder.example"],
    ["June Park", "admin", "june@briarcalder.example"],
  ].map(([name, role, email], index) => ({
    id: seedIds.staff[index],
    firm_id: seedIds.firm,
    name,
    role,
    email,
    is_active: true,
    created_at: createdAt,
  })),
  contacts: [
    {
      id: seedIds.contacts[0],
      firm_id: seedIds.firm,
      name: "Rosa Delgado",
      email: "rosa.delgado@example.com",
      phone: "+1 213 555 0101",
      company: "Delgado Studio",
      source: "website",
      notes: "New employment inquiry.",
      created_at: "2026-08-27T15:20:00.000Z",
    },
    {
      id: seedIds.contacts[1],
      firm_id: seedIds.firm,
      name: "Malcolm Price",
      email: "malcolm.price@example.com",
      phone: "+1 310 555 0102",
      company: null,
      source: "referral",
      notes: "Referred by a former client.",
      created_at: "2026-08-26T17:10:00.000Z",
    },
    {
      id: seedIds.contacts[2],
      firm_id: seedIds.firm,
      name: "Olivia Hart",
      email: "olivia.hart@example.com",
      phone: "+1 323 555 0103",
      company: "Hart Foods",
      source: "phone",
      notes: "Existing commercial client.",
      created_at: "2026-04-08T11:30:00.000Z",
    },
    {
      id: seedIds.contacts[3],
      firm_id: seedIds.firm,
      name: "Darius Kim",
      email: "darius.kim@example.com",
      phone: "+1 818 555 0104",
      company: null,
      source: "website",
      notes: "Personal injury inquiry.",
      created_at: "2026-08-29T08:40:00.000Z",
    },
    {
      id: seedIds.contacts[4],
      firm_id: seedIds.firm,
      name: "Celia Morgan",
      email: "celia.morgan@example.com",
      phone: "+1 424 555 0105",
      company: "Morgan Lighting",
      source: "email",
      notes: "Active litigation client.",
      created_at: "2026-02-12T10:00:00.000Z",
    },
    {
      id: seedIds.contacts[5],
      firm_id: seedIds.firm,
      name: "Noah Williams",
      email: "noah.williams@example.com",
      phone: "+1 626 555 0106",
      company: null,
      source: "website",
      notes: "Vague initial inquiry.",
      created_at: "2026-08-29T12:15:00.000Z",
    },
  ],
  interactions: [
    [
      0,
      "website",
      "inbound",
      "2026-08-27T15:20:00.000Z",
      "Submitted wrongful termination inquiry.",
    ],
    [
      1,
      "phone",
      "inbound",
      "2026-08-26T17:10:00.000Z",
      "Described injuries after a delivery-van collision.",
    ],
    [2, "email", "outbound", "2026-07-01T16:00:00.000Z", "Sent status update on contract dispute."],
    [
      3,
      "website",
      "inbound",
      "2026-08-29T08:40:00.000Z",
      "Asked for help after a rideshare collision.",
    ],
    [4, "meeting", "outbound", "2026-06-18T18:00:00.000Z", "Reviewed discovery plan with client."],
    [
      5,
      "website",
      "inbound",
      "2026-08-29T12:15:00.000Z",
      "Submitted a one-line request for a lawyer.",
    ],
  ].map(([contactIndex, channel, direction, occurredAt, summary], index) => ({
    id: seedIds.interactions[index],
    contact_id: seedIds.contacts[Number(contactIndex)],
    channel,
    direction,
    occurred_at: occurredAt,
    summary,
    created_at: occurredAt,
  })),
  leads: [
    {
      id: seedIds.leads[0],
      firm_id: seedIds.firm,
      contact_id: seedIds.contacts[0],
      source: "website",
      raw_json: {
        name: "Rosa Delgado",
        urgency: "Termination meeting is next week",
        matter_description: "Employer ended her role after she reported unpaid overtime.",
      },
      practice_area_guess: "employment",
      status: "review",
      created_at: "2026-08-27T15:20:00.000Z",
    },
    {
      id: seedIds.leads[1],
      firm_id: seedIds.firm,
      contact_id: seedIds.contacts[1],
      source: "referral",
      raw_json: {
        name: "Malcolm Price",
        urgency: "Medical bills are accumulating",
        matter_description:
          "Injured when a delivery van entered the intersection against a red light.",
      },
      practice_area_guess: "personal_injury",
      status: "review",
      created_at: "2026-08-26T17:10:00.000Z",
    },
    {
      id: seedIds.leads[2],
      firm_id: seedIds.firm,
      contact_id: seedIds.contacts[3],
      source: "website",
      raw_json: {
        name: "Darius Kim",
        urgency: "Police report available",
        matter_description: "Passenger injured in a rideshare collision two days ago.",
      },
      practice_area_guess: "personal_injury",
      status: "new",
      created_at: "2026-08-29T08:40:00.000Z",
    },
    {
      id: seedIds.leads[3],
      firm_id: seedIds.firm,
      contact_id: seedIds.contacts[5],
      source: "website",
      raw_json: {
        name: "Noah Williams",
        urgency: "Unknown",
        matter_description: "I need a lawyer. Please call.",
      },
      practice_area_guess: null,
      status: "new",
      created_at: "2026-08-29T12:15:00.000Z",
    },
  ],
  matters: [
    [0, "employment", "discovery", "2026-02-12T09:00:00.000Z", 4, "2026-07-11T18:00:00.000Z"],
    [
      1,
      "personal_injury",
      "records_collection",
      "2026-05-03T09:00:00.000Z",
      5,
      "2026-08-22T16:00:00.000Z",
    ],
    [
      2,
      "commercial_litigation",
      "pleadings",
      "2026-04-08T09:00:00.000Z",
      6,
      "2026-07-01T16:00:00.000Z",
    ],
    [
      4,
      "commercial_litigation",
      "discovery",
      "2026-02-12T09:00:00.000Z",
      2,
      "2026-06-18T18:00:00.000Z",
    ],
    [3, "personal_injury", "intake", "2026-08-29T09:00:00.000Z", null, "2026-08-29T08:40:00.000Z"],
  ].map(([contactIndex, matterType, stage, openedAt, staffIndex, lastContact], index) => ({
    id: seedIds.matters[index],
    firm_id: seedIds.firm,
    contact_id: seedIds.contacts[Number(contactIndex)],
    matter_type: matterType,
    stage,
    opened_at: openedAt,
    responsible_staff_id: staffIndex === null ? null : seedIds.staff[Number(staffIndex)],
    last_client_contact_at: lastContact,
    status: "open",
    created_at: openedAt,
  })),
  matter_tasks: [
    [0, "Confirm deposition availability", 4, "2026-08-20T17:00:00.000Z", null],
    [1, "Review updated treatment notes", 5, "2026-09-02T17:00:00.000Z", null],
    [2, "Draft response to motion", 6, "2026-09-05T17:00:00.000Z", null],
    [3, "Index production set", 8, "2026-08-25T17:00:00.000Z", "2026-08-24T15:00:00.000Z"],
  ].map(([matterIndex, title, staffIndex, dueAt, completedAt], index) => ({
    id: seedIds.tasks[index],
    matter_id: seedIds.matters[Number(matterIndex)],
    title,
    owner_staff_id: seedIds.staff[Number(staffIndex)],
    due_at: dueAt,
    completed_at: completedAt,
    created_at: "2026-08-10T09:00:00.000Z",
  })),
  matter_deadlines: [
    [0, "Discovery cutoff", "2026-09-04T17:00:00.000Z"],
    [2, "Opposition filing", "2026-09-12T17:00:00.000Z"],
    [3, "Expert disclosure", "2026-10-02T17:00:00.000Z"],
  ].map(([matterIndex, kind, dueAt], index) => ({
    id: seedIds.deadlines[index],
    matter_id: seedIds.matters[Number(matterIndex)],
    kind,
    due_at: dueAt,
    satisfied_at: null,
    created_at: "2026-08-10T09:00:00.000Z",
  })),
  documents: [
    {
      id: seedIds.documents[0],
      firm_id: seedIds.firm,
      matter_id: seedIds.matters[1],
      storage_path: "seed/price-emergency-room-records.pdf",
      filename: "Price - Emergency room records.pdf",
      mime: "application/pdf",
      uploaded_at: "2026-08-28T15:40:00.000Z",
      status: "review",
      created_at: "2026-08-28T15:40:00.000Z",
    },
    {
      id: seedIds.documents[1],
      firm_id: seedIds.firm,
      matter_id: seedIds.matters[2],
      storage_path: "seed/hart-motion-to-compel.pdf",
      filename: "Hart Foods - Motion to compel.pdf",
      mime: "application/pdf",
      uploaded_at: "2026-08-28T11:10:00.000Z",
      status: "review",
      created_at: "2026-08-28T11:10:00.000Z",
    },
    {
      id: seedIds.documents[2],
      firm_id: seedIds.firm,
      matter_id: seedIds.matters[0],
      storage_path: "seed/delgado-payroll-export.pdf",
      filename: "Delgado - Payroll export.pdf",
      mime: "application/pdf",
      uploaded_at: "2026-08-29T10:00:00.000Z",
      status: "new",
      created_at: "2026-08-29T10:00:00.000Z",
    },
    {
      id: seedIds.documents[3],
      firm_id: seedIds.firm,
      matter_id: null,
      storage_path: "seed/unmatched-demand-letter.pdf",
      filename: "Demand letter - August 29.pdf",
      mime: "application/pdf",
      uploaded_at: "2026-08-29T13:10:00.000Z",
      status: "new",
      created_at: "2026-08-29T13:10:00.000Z",
    },
  ],
  document_requests: [
    [0, "Personnel file", "2026-07-15T16:00:00.000Z", null],
    [1, "Complete billing ledger", "2026-08-10T16:00:00.000Z", null],
    [2, "Executed contract", "2026-06-10T16:00:00.000Z", "2026-06-18T16:00:00.000Z"],
  ].map(([matterIndex, docType, requestedAt, receivedAt], index) => ({
    id: seedIds.requests[index],
    matter_id: seedIds.matters[Number(matterIndex)],
    doc_type: docType,
    requested_at: requestedAt,
    received_at: receivedAt,
    created_at: requestedAt,
  })),
  agent_runs: [
    ["intake-brief", "lead", seedIds.leads[0], "2026-08-27T15:22:00.000Z"],
    ["intake-brief", "lead", seedIds.leads[1], "2026-08-26T17:12:00.000Z"],
    ["document-routing", "document", seedIds.documents[0], "2026-08-28T15:42:00.000Z"],
    ["document-routing", "document", seedIds.documents[1], "2026-08-28T11:12:00.000Z"],
    ["stalled-work", "firm", seedIds.firm, "2026-08-29T07:00:00.000Z"],
  ].map(([agent, subjectType, subjectId, startedAt], index) => ({
    id: seedIds.runs[index],
    agent,
    subject_type: subjectType,
    subject_id: subjectId,
    model: "reference-review-output",
    status: "review",
    started_at: startedAt,
    finished_at: startedAt,
    input_tokens: 0,
    output_tokens: 0,
    cost_usd: 0,
    created_at: startedAt,
  })),
  briefs: [
    {
      id: seedIds.briefs[0],
      lead_id: seedIds.leads[0],
      run_id: seedIds.runs[0],
      qualification_json: { fit_score: 8, urgency: "high", conflict_check_required: true },
      brief_md:
        "## Who\nRosa Delgado, former operations lead.\n\n## What\nPotential retaliation and unpaid overtime claim.",
      next_action: "schedule_consult",
      reply_draft: "Thank you, Rosa. We would like to schedule a call after our conflict check.",
      confidence: 0.88,
      status: "review",
      created_at: "2026-08-27T15:23:00.000Z",
    },
    {
      id: seedIds.briefs[1],
      lead_id: seedIds.leads[1],
      run_id: seedIds.runs[1],
      qualification_json: { fit_score: 7, urgency: "medium", conflict_check_required: true },
      brief_md:
        "## Who\nMalcolm Price, referred by a former client.\n\n## What\nVehicle collision with ongoing treatment.",
      next_action: "request_info",
      reply_draft:
        "Thank you, Malcolm. Please send the collision report and treatment dates for review.",
      confidence: 0.79,
      status: "review",
      created_at: "2026-08-26T17:13:00.000Z",
    },
  ],
  document_results: [
    {
      id: seedIds.documentResults[0],
      document_id: seedIds.documents[0],
      run_id: seedIds.runs[2],
      classification_json: {
        doc_type: "medical_record",
        signed: null,
        parties: ["Malcolm Price"],
        dates: [],
        amounts: [],
        key_fields: { provider: "Central Los Angeles Medical Center" },
        is_scanned: false,
        confidence: 0.93,
        evidence: [
          {
            field: "provider",
            quote: "Central Los Angeles Medical Center",
            page: 1,
          },
        ],
      },
      extracted_json: { provider: "Central Los Angeles Medical Center", pages: 18 },
      completeness_json: {
        satisfied: ["medical_record"],
        missing: [
          "engagement_agreement",
          "identity_document",
          "incident_report",
          "insurance_document",
          "medical_bill",
          "wage_record",
        ],
        stale_requests: [],
      },
      routing_json: {
        matter_id: seedIds.matters[1],
        reviewer_role: "paralegal",
        priority: "normal",
        reason: "Unique client name and linked personal injury matter.",
      },
      request_draft: null,
      confidence: 0.93,
      status: "review",
      created_at: "2026-08-28T15:43:00.000Z",
    },
    {
      id: seedIds.documentResults[1],
      document_id: seedIds.documents[1],
      run_id: seedIds.runs[3],
      classification_json: {
        doc_type: "pleading_or_court_notice",
        signed: null,
        parties: ["Hart Foods"],
        dates: ["2026-09-18"],
        amounts: [],
        key_fields: { filing_party: "Plaintiff" },
        is_scanned: false,
        confidence: 0.9,
        evidence: [
          {
            field: "dates",
            quote: "Hearing date September 18, 2026",
            page: 1,
          },
        ],
      },
      extracted_json: { filing_party: "Plaintiff", hearing_date: "2026-09-18" },
      completeness_json: {
        satisfied: ["pleading_or_court_notice"],
        missing: [
          "engagement_agreement",
          "identity_document",
          "contract",
          "invoice_or_payment_record",
          "discovery_document",
        ],
        stale_requests: [],
      },
      routing_json: {
        matter_id: seedIds.matters[2],
        reviewer_role: "partner",
        priority: "high",
        reason: "Explicit hearing date and unique client match.",
      },
      request_draft: null,
      confidence: 0.9,
      status: "review",
      created_at: "2026-08-28T11:13:00.000Z",
    },
  ],
  stalled_reports: [
    {
      id: seedIds.stalledReport,
      firm_id: seedIds.firm,
      run_id: seedIds.runs[4],
      report_date: "2026-08-29",
      summary_md: "Four matters need an owner decision before Monday.",
      items_json: { total: 4, high: 2, medium: 2 },
      status: "review",
      created_at: "2026-08-29T07:01:00.000Z",
    },
  ],
  stalled_items: [
    {
      id: seedIds.stalledItems[0],
      report_id: seedIds.stalledReport,
      matter_id: seedIds.matters[0],
      kind: "overdue_task",
      severity: "high",
      evidence_json: { confidence: 0.97, overdue_days: 9, task: "Confirm deposition availability" },
      drafted_action: "Ask Avery Chen to confirm deposition availability today.",
      created_at: "2026-08-29T07:02:00.000Z",
    },
    {
      id: seedIds.stalledItems[1],
      report_id: seedIds.stalledReport,
      matter_id: seedIds.matters[0],
      kind: "at_risk_deadline",
      severity: "high",
      evidence_json: { confidence: 0.95, deadline: "Discovery cutoff", due_at: "2026-09-04" },
      drafted_action: "Partner should confirm the discovery plan before the cutoff.",
      created_at: "2026-08-29T07:03:00.000Z",
    },
    {
      id: seedIds.stalledItems[2],
      report_id: seedIds.stalledReport,
      matter_id: seedIds.matters[2],
      kind: "stale_client_contact",
      severity: "medium",
      evidence_json: { confidence: 0.89, days_since_contact: 59 },
      drafted_action: "Prepare a short status-call agenda for Jordan Miles.",
      created_at: "2026-08-29T07:04:00.000Z",
    },
    {
      id: seedIds.stalledItems[3],
      report_id: seedIds.stalledReport,
      matter_id: seedIds.matters[4],
      kind: "ownerless_matter",
      severity: "medium",
      evidence_json: { confidence: 1, responsible_staff_id: null },
      drafted_action: "Assign an owner before any follow-up is sent.",
      created_at: "2026-08-29T07:05:00.000Z",
    },
  ],
} as const;
